In [1]:
!wget  https://www.dropbox.com/s/5721wcs2guuykzl/stacksample.zip?dl=0

--2020-12-31 02:50:15--  https://www.dropbox.com/s/5721wcs2guuykzl/stacksample.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/5721wcs2guuykzl/stacksample.zip [following]
--2020-12-31 02:50:15--  https://www.dropbox.com/s/raw/5721wcs2guuykzl/stacksample.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucab0ec4e0a55ca586b5d00ad233.dl.dropboxusercontent.com/cd/0/inline/BGGpHYB9x-p90HvtupEKhbzJLTOUHcFWGbBgAk_I4qttiXmD-UGAY1QU6rsGo1hC79cFBHJRHprgiv8K35HCBfqxInACpY9IGtRTzNLvi3uB7g/file# [following]
--2020-12-31 02:50:16--  https://ucab0ec4e0a55ca586b5d00ad233.dl.dropboxusercontent.com/cd/0/inline/BGGpHYB9x-p90HvtupEKhbzJLTOUHcFWGbBgAk_I4qttiXmD-UGAY1QU6rsGo1hC79cFBHJRHprgiv8K35HCBfqxInACpY9IGtRTzNLvi3uB7g/file
Re

In [2]:
!unzip stacksample.zip?dl=0

Archive:  stacksample.zip?dl=0
  inflating: Answers.csv             
  inflating: Questions.csv           
  inflating: Tags.csv                


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [4]:
ques = pd.read_csv(r'/content/Questions.csv',encoding='latin-1')
ans= pd.read_csv(r'/content/Answers.csv',encoding='latin-1')
tags = pd.read_csv(r'/content/Tags.csv',encoding='latin-1')

In [5]:
ques.head()

Id  ...                                               Body
0   80  ...  <p>I've written a database generation script i...
1   90  ...  <p>Are there any really good tutorials explain...
2  120  ...  <p>Has anyone got experience creating <strong>...
3  180  ...  <p>This is something I've pseudo-solved many t...
4  260  ...  <p>I have a little game written in C#. It uses...

[5 rows x 7 columns]

In [6]:
ques['Body'][120]

"<p>I want to rename a database, but keep getting the error that 'couldn't get exclusive lock' on the database, which implies there is some connection(s) still active.</p>\n\n<p>How can I kill all the connections to the database so that I can rename it?</p>\n"

In [7]:
ans.head()

Id  OwnerUserId  ... Score                                               Body
0   92         61.0  ...    13  <p><a href="http://svnbook.red-bean.com/">Vers...
1  124         26.0  ...    12  <p>I wound up using this. It is a kind of a ha...
2  199         50.0  ...     1  <p>I've read somewhere the human eye can't dis...
3  269         91.0  ...     4  <p>Yes, I thought about that, but I soon figur...
4  307         49.0  ...    28  <p><a href="http://www.codeproject.com/Article...

[5 rows x 6 columns]

In [8]:
ques[ques['Score']== 5]

Id  ...                                               Body
73           6890  ...  <p>I have some code for starting a thread on t...
97           9750  ...  <p>I was reading Joel's book where he was sugg...
109         10870  ...  <p>Once I've called <code>DragManager.acceptDr...
116         11430  ...  <p>Does SQL Server 2008 ship with the .NET 3.5...
171         16330  ...  <p>If you had to provide a wizard like form en...
...           ...  ...                                                ...
1261159  40071760  ...  <p>I have the following resources:</p>\n\n<pre...
1262160  40094470  ...  <p>I have a method:</p>\n\n<pre><code>@gen.cor...
1262745  40108070  ...  <p>In a Pyhton program I need to get the accum...
1263253  40120130  ...  <p>In an C++ MFC project I'm using <a href="ht...
1263609  40129230  ...  <p>I want to manage topic subscription from th...

[20203 rows x 7 columns]

In [9]:
ans[ans['Id']== 269]

Id  OwnerUserId  ... Score                                               Body
3  269         91.0  ...     4  <p>Yes, I thought about that, but I soon figur...

[1 rows x 6 columns]

In [10]:
tags['Tag'].value_counts()[0:20]

javascript       124155
java             115212
c#               101186
php               98808
android           90659
jquery            78542
python            64601
html              58976
c++               47591
ios               47009
mysql             42464
css               42308
sql               35782
asp.net           29970
objective-c       26922
ruby-on-rails     25789
.net              24059
c                 23238
iphone            21539
angularjs         20345
Name: Tag, dtype: int64

In [11]:
ques.shape,ans.shape,tags.shape

((1264216, 7), (2014516, 6), (3750994, 2))

In [12]:
ques['Score'].value_counts()[0:100]

 0     591710
 1     281042
 2     125000
 3      61182
-1      43779
        ...  
 82        39
 85        38
 83        37
 93        32
 88        31
Name: Score, Length: 100, dtype: int64

In [13]:
tags['Tag'].value_counts()[:10].index

Index(['javascript', 'java', 'c#', 'php', 'android', 'jquery', 'python',
       'html', 'c++', 'ios'],
      dtype='object')

In [14]:
top10_tags = list(tags['Tag'].value_counts()[:10].index)
print(top10_tags)

['javascript', 'java', 'c#', 'php', 'android', 'jquery', 'python', 'html', 'c++', 'ios']


In [15]:
top10_tags = list(tags['Tag'].value_counts()[:10].index)
print(top10_tags)

new_tags = tags[tags['Tag'].isin(top10_tags)]
new_tags.reset_index(drop=True, inplace=True)


['javascript', 'java', 'c#', 'php', 'android', 'jquery', 'python', 'html', 'c++', 'ios']


In [16]:
q1 = ques

In [17]:
ques.drop(columns=['OwnerUserId', 'CreationDate', 'ClosedDate', 'Score'], inplace=True)

In [18]:
ques.isnull().sum()

Id       0
Title    0
Body     0
dtype: int64

In [19]:
new_tags.isnull().sum()

Id     0
Tag    0
dtype: int64

In [20]:
df = ques.merge(new_tags, on='Id')
print(df.shape)
df.head()

df = df[0:round(len(df)/4)]

(826739, 4)


In [21]:
len(df)

df.shape

(206685, 4)

In [22]:
df.isnull().sum()

Id       0
Title    0
Body     0
Tag      0
dtype: int64

In [23]:
df.drop(['Id'],axis = 1,inplace=True)

In [24]:
#Data splitting into training and validation sets

train_size = round(df.shape[0]*0.8)
test_size = df.shape[0] - train_size

X = df.drop(['Tag'],axis=1)
Y = df['Tag']


#Numericacl representation of the tag values
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()
Y = LE.fit_transform(Y)

X_train, X_test = X[:train_size], X[train_size:]
Y_train, Y_test = Y[:train_size], Y[train_size:]

In [25]:
Y

array([1, 2, 1, ..., 8, 8, 8])

In [26]:
X_train.head()

Title                                               Body
0  Adding scripting functionality to .NET applica...  <p>I have a little game written in C#. It uses...
1          Should I use nested classes in this case?  <p>I am working on a collection of classes use...
2                Automatically update version number  <p>I would like the version property of my app...
3  How do I connect to a database and loop over a...  <p>What's the simplest way to connect and quer...
4  How to get the value of built, encoded ViewState?  <p>I need to grab the base64-encoded represent...

In [27]:
X_train.shape, X_test.shape,Y_train.shape, Y_test.shape

((165348, 2), (41337, 2), (165348,), (41337,))

In [28]:
!pip install beautifulsoup4

In [29]:
from bs4 import BeautifulSoup

# Converting html to text in the body
X_train['Body'] = X_train['Body'].apply(lambda x: BeautifulSoup(x).get_text())
X_test['Body'] = X_test['Body'].apply(lambda x: BeautifulSoup(x).get_text())

X_train['Title'] = X_train['Title'].apply(lambda x: BeautifulSoup(x).get_text())
X_test['Title'] = X_test['Title'].apply(lambda x: BeautifulSoup(x).get_text())

In [32]:
#Removing Punctuations

X_train.replace('[^a-zA-Z]',' ', regex=True, inplace=True)
X_test.replace('[^a-zA-Z]',' ', regex=True, inplace=True)

In [30]:
#Converting to lower case characters

for index in X_train.columns:
  X_train[index] = X_train[index].str.lower()

for index in X_test.columns:
  X_test[index] = X_test[index].str.lower()

In [31]:
#Removing multiple blank spaces

X_train = X_train.replace('\s+', ' ', regex=True)
X_test = X_test.replace('\s+', ' ', regex=True)

In [33]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
from nltk import sent_tokenize, word_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [34]:
type(X_train)

pandas.core.frame.DataFrame

In [35]:
#Excluding stop words
stop_words = set(stopwords.words('english')) 
len(stop_words)
X_train['Body'] = X_train['Body'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))
X_train['Title'] = X_train['Title'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))

X_test['Body'] = X_test['Body'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))
X_test['Title'] = X_test['Title'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))

In [36]:
#Stemming to roots

stemmer = nltk.SnowballStemmer(language='english')

X_train['Body'] = X_train['Body'].apply(lambda x: ' '.join(stemmer.stem(term) for term in x.split()))
X_train['Title'] = X_train['Title'].apply(lambda x: ' '.join(stemmer.stem(term) for term in x.split()))

X_test['Body'] = X_test['Body'].apply(lambda x: ' '.join(stemmer.stem(term) for term in x.split()))
X_test['Title'] = X_test['Title'].apply(lambda x: ' '.join(stemmer.stem(term) for term in x.split()))

In [37]:
#Appending lines
train_lines = []
for row in range(0,X_train.shape[0]):
  train_lines.append(' '.join(str(x) for x in X_train.iloc[row,:]))

test_lines = []
for row in range(0,X_test.shape[0]):
  test_lines.append(' '.join(str(x) for x in X_test.iloc[row,:]))

In [38]:
#Model implementation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Activation, Dense, Dropout, Flatten, Embedding, BatchNormalization 
from tensorflow.keras.models import Model

from keras.preprocessing.text import Tokenizer

In [39]:
max_len_train = len(max(train_lines,key=len))
max_len_test = len(max(test_lines,key=len))
print(max_len_train, max_len_test)

28133 22706


In [40]:
sent_lens=[]
for sent in train_lines:
    sent_lens.append(len(word_tokenize(sent)))
print(max(sent_lens))

4557


In [41]:
print(np.quantile(sent_lens,0.98))

434.0


In [42]:
max_len = 434
tok = Tokenizer(char_level=False,split=' ')
tok.fit_on_texts(train_lines)
sequences_train = tok.texts_to_sequences(train_lines)

In [43]:
vocab_len=len(tok.index_word.keys())
print(vocab_len) 

302100


In [44]:
sequences_matrix_train = pad_sequences(sequences_train,padding='pre',maxlen=max_len)
print(sequences_matrix_train)

[[   0    0    0 ...   49  132  458]
 [   0    0    0 ... 1613  238  242]
 [   0    0    0 ...  125    6 1225]
 ...
 [   0    0    0 ...   93   78   72]
 [   0    0    0 ...   14 1804   53]
 [   0    0    0 ...  100  243 1351]]


In [45]:
sequences_test = tok.texts_to_sequences(test_lines)
sequences_matrix_test = pad_sequences(sequences_test,padding='pre',maxlen=max_len)
print(sequences_matrix_test)

[[   0    0    0 ...  190   60   53]
 [   0    0    0 ...  322 2626  181]
 [   0    0    0 ...   15  208   32]
 ...
 [   0    0    0 ...  124  300  125]
 [   0    0    0 ...   53  379   86]
 [   0    0    0 ... 1344   82  203]]


In [46]:
model = Sequential()
model.add(Embedding(vocab_len+1,200,input_length=max_len))
model.add(Flatten())
model.add(Dense(400,activation='relu'))
model.add(Dense(150,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

In [47]:
from tensorflow.keras.utils import to_categorical

Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)

In [48]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 434, 200)          60420200  
_________________________________________________________________
flatten (Flatten)            (None, 86800)             0         
_________________________________________________________________
dense (Dense)                (None, 400)               34720400  
_________________________________________________________________
dense_1 (Dense)              (None, 150)               60150     
_________________________________________________________________
dropout (Dropout)            (None, 150)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1510      
Total params: 95,202,260
Trainable params: 95,202,260
Non-trainable params: 0
____________________________________________

In [49]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [50]:
import tensorflow
h = model.fit(sequences_matrix_train,Y_train,
              validation_data=(sequences_matrix_test,Y_test),
              epochs=4, batch_size=800,
              callbacks=[
                         tensorflow.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=2)
    ])

Epoch 1/4
207/207 [==============================] - 686s 3s/step - loss: 1.9455 - accuracy: 0.3531 - val_loss: 0.7567 - val_accuracy: 0.7447
Epoch 2/4
207/207 [==============================] - 688s 3s/step - loss: 0.5993 - accuracy: 0.7950 - val_loss: 0.6734 - val_accuracy: 0.7678
Epoch 3/4
207/207 [==============================] - 766s 4s/step - loss: 0.4392 - accuracy: 0.8351 - val_loss: 0.6791 - val_accuracy: 0.7682
Epoch 4/4
207/207 [==============================] - 712s 3s/step - loss: 0.3487 - accuracy: 0.8541 - val_loss: 0.7158 - val_accuracy: 0.7668
